### ISSUE TITLE
Publish SHA256 sums for kubectl plugins

### ISSUE THREAD

**Issue by ameukam** [cert-manager/release#16]
With the new release of the kubectl plugins, it will be interesting to distributing templates on [krew index](https://krew.sigs.k8s.io/).

One requirement about publishing the plugins in krew is to provide a sha256 sum for every plugin: https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/#specifying-plugin-download-options. 

cc @munnerz

**Comment by hzhou97** [comment]
The plugin is now being published on krew index, it's now a part of the release process to update the SHA256 sum on the plugin manifest in the krew index repo. Is there still need to publish the SHA256 sums?
/priority awaiting-more-evidence

**Comment by ameukam** [comment]
@hzhou97 I no longer need the SHA256 sums to be published. Thank you!
