### ISSUE TITLE
Cmctl isn't in the main repository anymore

### ISSUE THREAD

**Issue by maelvls** [cert-manager/release#168]
While releasing 1.15.0-alpha.0, I hit the following issue:

https://console.cloud.google.com/cloud-build/builds/78e0c8c3-c8b9-403a-9df8-e89bd4c2eba0?project=cert-manager-release

```
Step #3: 2024/03/29 10:37:22 Release validation failed:
Step #3: 2024/03/29 10:37:22   - No ctl binaries found in release - this is probably an error!
```

The cmctl binaries should only be pushed for cert-manager 1.14 and below, not for 1.15 and above.

**Comment by maelvls** [comment]
I've started working on skipping the cmctl binaries in #169.

**Comment by inteon** [comment]
fixed in https://github.com/cert-manager/release/pull/169 and https://github.com/cert-manager/release/pull/177
