### ISSUE TITLE
Build and release kubectl plugin for Apple Silicon

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/release#25]
`kubectl` itself is now built and released for Apple Silicon https://github.com/kubernetes/kubernetes/pull/97743.

We already have `darwin/arm` in the list of client platform in `cert-manager` codebase [here](https://github.com/jetstack/cert-manager/blob/master/build/platforms.bzl#L38) so this would probably be just a matter of adding it to the release tooling [here-ish](https://github.com/cert-manager/release/blob/master/pkg/release/consts.go#L86) and finding someone with an M1 Mac willing to test the new binary.

**Comment by munnerz** [comment]
Today is M1 Mac testing day for me 😊 happy to run some tests if you've got some commands to run

**Comment by irbekrm** [comment]
Hey @munnerz thanks for the offer- sorry we haven't quite sorted out yet the testing on M1 Mac ourselves!

I ran `cmrel stage` from #26 and we now have a devel build of the kubectl plugin for `darwin/arm64` [here](https://console.cloud.google.com/storage/browser/cert-manager-release/stage/gcb/devel/b95836421f7f3d2bbbebaa4fa3cca7128e3a97ad?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=1&project=cert-manager-release&prefix=&forceOnObjectsSortingFiltering=false) - not sure if you still have access to that bucket? If you had a chance to see if the plugin works that would be really kind 😄 

There is also jetstack/cert-manager/pull/3871 where I tried to add darwin/arm to test platforms to allow running tests without the platform flag, but someone already reported that [it's not working](https://github.com/jetstack/cert-manager/pull/3871), think I might need to dig more into that.

**Comment by munnerz** [comment]
Sorry for the late response - taking a look at that link, I don't see a `darwin/arm64` variant in there 🤔
<img width="515" alt="Screenshot 2021-05-13 at 15 09 58" src="https://user-images.githubusercontent.com/203583/118137667-5fc86b00-b3fd-11eb-989b-dd3dbe394ab6.png">

**Comment by irbekrm** [comment]
I cannot recall what I was thinking - I'm sure I checked whether it's there, but must have somehow missed the fact that it's _not there_ 😆

**Comment by irbekrm** [comment]
Re-opening as this wasn't fixed.

Related issue https://github.com/jetstack/cert-manager/issues/4052
