### ISSUE TITLE
Create cert-manager specific testing infrastructure

### ISSUE THREAD

**Issue by jakexks** [cert-manager/release#27]
To prepare for the cert-manager release automation drive and the separation of cert-manager prow from jetstack prow, we should have automated cert-manager test / release infrastructure in place.

Progress

- [x] Investigate what we currently have
- [x] Try using official GKE terraform modules - dislike the opinionated setup and resulting  cost
- [x] Infrastructure as code - k8s cluster
  - [x] Investigate best practice for GKE
  - [x] Deploy / destroy test cluster with tf
  - [x] Investigate OIDC on GKE - kube-oidc-proxy + gangway + dex + github oauth
  - [x] integrate OIDC into build.
- [x] deployments as code - identity provider for k8s api access (kubectl) deployed
- [x] integrate identity provider with Github - org membership grants read access

Next steps
- [x] Create the repository https://github.com/cert-manager/infrastructure
- [x] Push all config for infra in to the https://github.com/cert-manager/infrastructure
- [x] Port prow jobs to new testing repo under cert-manager org https://github.com/cert-manager/testing
- [x] Create github bot account (in CNCF 1Password)
- [x] Run the new infra
- [x] Decommission old prow setup

**Comment by munnerz** [comment]
Awesome to see 😄 when you say being an org member grants read access to the cluster - is that for _all_ org members? Could we use a GitHub team within the org instead, so we can have more granular access controls?

I'm nervous about exposing access to the cluster running prow (this contains credentials like the bot user, which is an org admin) to _anyone_ in the org (and I think this will implicitly 'raise the bar' of being an org member too, which may make us less likely to have people as part of it)

**Comment by jakexks** [comment]
A Github team makes much more sense 👍

**Comment by SgtCoDFish** [comment]
I've renamed this since I think it addresses the more challenging technical issue of moving the testing across. Release infra should be _much_ simpler; I've created #50 to track that.

**Comment by maelvls** [comment]
Seems like we are getting close!

**Comment by inteon** [comment]
All prow config and yaml lives here now: https://github.com/cert-manager/testing
The cluster itself is defined here: https://github.com/cert-manager/infrastructure/tree/main/gcp
The GCP access is managed here: https://github.com/cert-manager/infrastructure/blob/3506da56193e074f381429361f6fed5d16322702/gcp/variables.tf#L3-L9
The GCP clusters are hosted under the CNCF GCP project.

That should finalize the migration to CNCF-owned infrastructure, more info can be found here: https://github.com/cert-manager/infrastructure/issues/44
