### ISSUE TITLE
Move cert-manager-release infrastructure to CNCF's GCP account

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/release#50]
CNCF have offered for us to move our `cert-manager-release` GCP project to live under the CNCF's GCP account. `cert-manager-release` is currently Jetstack internal.

> We can migrate you to the CNCF GCP account where a dedicated project will be created for you (actually, if you have one - we’ll migrate it). To proceed, please add me (email removed) as an owner and I’ll take it from there. 
> CNCF will cover [the costs], no worries
> [Permissions and resources should remain unchanged] but if not - I can easily add all the necessary folks there 

This issue is to track that migration, and to provide a place for any discussion relating to that move.

**Comment by SgtCoDFish** [comment]
An alternative to porting the infrastructure would be to start fresh in a new project, which was discussed in cert-manager standup  24/09. We'll discuss this next week and decide on a path forwards.

**Comment by SgtCoDFish** [comment]
We got the go-ahead to move today (28/09); I'll contact the CNCF to get the ball rolling.

**Comment by SgtCoDFish** [comment]
Update again: as far as we know the permissions are set on the jetstack side and we're waiting for the actual org move to happen.

**Comment by SgtCoDFish** [comment]
Update again: still continuing to chase.

**Comment by SgtCoDFish** [comment]
Update: given the upcoming holiday period we'll revisit in January 2022

**Comment by SgtCoDFish** [comment]
Update:

> if you can figure out if something else is needed from your end, it would be great as we’re still stuck with this one 

We'll see if we can figure anything out on our end.

**Comment by inteon** [comment]
All release infrastructure has been moved to the CNCF GCP organisation.
